### PR TITLE
Fix occasional IndexError on empty segments

### PR DESCRIPTION
**Pull request by guillaumekln**

### CODE REVIEW

**Comment by junchen6072** [comment]
Hi, I came into this error recently, is this one good to merge?

**Comment by junchen6072** [comment]
I see, I guess other changes are also waiting for openai/whisper, like this one?
https://github.com/guillaumekln/faster-whisper/pull/225

**Comment by guillaumekln** [comment]
Yes

**Comment by guillaumekln** [comment]
We can merge this one already since it does not change the behavior.

**Pull request merged**
